<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="unit_suite1.Test_unit_suite1-20200806201551" tests="2" time="0.000">
	<testcase classname="unit_suite1.Test_unit_suite1" name="test_helloworld" time="0.000"/>
	<testcase classname="unit_suite1.Test_unit_suite1" name="test_no_doc_string" time="0.000"/>
	<system-out>
<![CDATA[hellworld
no_doc_string
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="unit_suite3.Test_unit_suite3-20200806201551" tests="2" time="0.000">
	<testcase classname="unit_suite3.Test_unit_suite3" name="test_sample_1" time="0.000"/>
	<testcase classname="unit_suite3.Test_unit_suite3" name="test_sample_0" time="0.000">
		<error message="shouldn't happen" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/logic/_workspace/python-playlist/unittest-json-reporting-tryout/src/test/unit/unit_suite3.py", line 13, in test_sample_0
    self.fail("shouldn't happen")
AssertionError: shouldn't happen
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[hellworld
no_doc_string
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="unit_suite4.Test_unit_suite4-20200806201551" tests="2" time="0.000">
	<testcase classname="unit_suite4.Test_unit_suite4" name="test_sample_1" time="0.000"/>
	<testcase classname="unit_suite4.Test_unit_suite4" name="test_sample_0" time="0.000">
		<error message="shouldn't happen" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/logic/_workspace/python-playlist/unittest-json-reporting-tryout/src/test/unit/unit_suite4.py", line 13, in test_sample_0
    self.fail("shouldn't happen")
AssertionError: shouldn't happen
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[hellworld
no_doc_string
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="unit_suite2.Test_unit_suite2-20200806201551" tests="1" time="0.000">
	<testcase classname="unit_suite2.Test_unit_suite2" name="test_sample_0" time="0.000">
		<error message="shouldn't happen" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/logic/_workspace/python-playlist/unittest-json-reporting-tryout/src/test/unit/unit_suite2.py", line 13, in test_sample_0
    self.fail("shouldn't happen")
AssertionError: shouldn't happen
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[hellworld
no_doc_string
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
